"use client";
import Link from "next/link";import {Header} from "@/components/Header";import {ProductVisual} from "@/components/Brand";import {useGame} from "@/features/game/GameProvider";
const sections=[
 ["BRONGO คืออะไร",<p key="a">BRONGO มีตัวยาสำคัญชื่อ carbocisteine lysine เป็นยาละลายเสมหะ ความแรง 450 มิลลิกรัมต่อ 5 มิลลิลิตร ในรูปแบบยาน้ำเชื่อม</p>],
 ["ใช้เพื่ออะไร",<p key="b">ใช้เพื่อละลายเสมหะในโรคที่ทางเดินหายใจมีความผิดปกติทั้งชนิดเฉียบพลันหรือเรื้อรัง ซึ่งส่งผลให้มีเสมหะเหนียวข้นหรือมากผิดปกติ</p>],
 ["วิธีใช้",<ul key="c"><li>ควรใช้ยาตามคำแนะนำของแพทย์หรือเภสัชกร</li><li>ผู้ใหญ่: ครั้งละ 30 มล. วันละ 1 ครั้ง หรือ 15 มล. วันละ 2 ครั้ง</li><li>เด็ก 1–5 ปี: 2.5 มล. วันละ 2 ครั้ง</li><li>เด็กมากกว่า 5 ปี: 5 มล. วันละ 2 ครั้ง</li><li>ไม่ควรใช้ในเด็กอายุต่ำกว่า 1 ปี</li></ul>],
 ["การเก็บรักษา",<ul key="d"><li>เก็บในบรรจุภัณฑ์เดิม ในที่แห้ง ป้องกันแสง และอุณหภูมิไม่เกิน 30°C</li><li>เก็บให้พ้นมือเด็ก</li></ul>],
 ["ข้อควรระวัง",<ul key="e"><li>ปรึกษาแพทย์หรือเภสัชกรก่อนใช้ หากเป็นโรคหอบหืด เคยเป็นแผลในกระเพาะ หญิงตั้งครรภ์ระยะแรก หรือให้นมบุตร</li><li>ไม่แนะนำให้ใช้ร่วมกับยาแก้ไอชนิดกดอาการไอโดยไม่ได้รับคำแนะนำ</li></ul>],
 ["อาการที่ต้องหยุดยาและพบแพทย์ทันที",<ul key="f"><li>ลมพิษ หรือบวมที่ใบหน้า เปลือกตา หรือริมฝีปาก</li><li>หน้ามืด เป็นลม แน่นหน้าอก หรือหายใจลำบาก</li><li>ผื่นแดง ตุ่มพอง ผิวหนังหลุดลอก หรือเลือดออกผิดปกติ</li></ul>],
 ["คำถามที่พบบ่อย: คะแนน 100% หมายถึงเลือกครบสูตรหรือไม่?",<p key="g">ไม่จำเป็น คะแนน 100% หมายถึงทุกอย่างที่คุณเลือกมีอยู่ใน BRONGO แม้จะเลือกเพียงรายการเดียว</p>],
 ["คำถามที่พบบ่อย: คะแนนนี้ใช้เลือกยาได้หรือไม่?",<p key="h">ไม่ได้ เกมนี้ให้ความรู้เท่านั้น การเลือกใช้ยาควรปรึกษาแพทย์หรือเภสัชกร</p>]
];
export default function Brongo(){const{reset}=useGame();return <><Header/><main id="main" className="page-shell"><header className="page-head"><p className="eyebrow">PRODUCT INFORMATION</p><h1>ข้อมูลยา BRONGO</h1></header><section className="product-summary"><ProductVisual/><div><h2>BRONGO</h2><p>ยาน้ำเชื่อมที่มี carbocisteine lysine 450 มิลลิกรัมต่อ 5 มิลลิลิตร ใช้เพื่อละลายเสมหะในภาวะที่มีเสมหะเหนียวข้นหรือมากผิดปกติ</p></div></section><p className="notice">ข้อมูลต่อไปนี้เป็นข้อมูลโดยย่อจากเอกสารกำกับยา หากมีข้อสงสัยให้ปรึกษาแพทย์หรือเภสัชกร</p><section className="accordion">{sections.map(([title,body])=><details key={String(title)}><summary>{title}</summary><div className="detail-body">{body}</div></details>)}</section><p><b>ผู้ผลิต:</b> บริษัท ไบโอแลป จำกัด จังหวัดสมุทรปราการ<br/><b>ผู้จัดจำหน่าย:</b> บริษัท อินเตอร์ฟาร์มาแคร์ จำกัด<br/><b>เอกสารข้อมูลยาปรับปรุงล่าสุด:</b> ตุลาคม 2567</p><div className="result-actions"><Link className="button primary" href="/mix" onClick={reset}>ผสมสูตรใหม่</Link><Link className="button secondary" href="/result">กลับไปดูผลลัพธ์</Link></div></main></>}
